import {
  Smartphone,
  Wifi,
  Ticket,
  Gamepad2,
  Zap,
  Wallet,
  Receipt,
  Droplets,
  HeartPulse,
} from 'lucide-react';

export const SERVICES = [
  {
    id: 'pulsa',
    label: 'Pulsa',
    description: 'Isi pulsa semua operator',
    icon: Smartphone,
    color: 'bg-blue-500',
    type: 'prepaid',
    customerLabel: 'Nomor HP',
    customerPlaceholder: '08xxxxxxxxxx',
    minLength: 10,
  },
  {
    id: 'data',
    label: 'Paket Data',
    description: 'Kuota internet semua operator',
    icon: Wifi,
    color: 'bg-purple-500',
    type: 'prepaid',
    customerLabel: 'Nomor HP',
    customerPlaceholder: '08xxxxxxxxxx',
    minLength: 10,
  },
  {
    id: 'ewallet',
    label: 'E-Wallet',
    description: 'Top up Dana, OVO, GoPay & lainnya',
    icon: Wallet,
    color: 'bg-emerald-500',
    type: 'prepaid',
    customerLabel: 'Nomor HP',
    customerPlaceholder: '08xxxxxxxxxx',
    minLength: 10,
  },
  {
    id: 'voucher',
    label: 'Voucher',
    description: 'Voucher digital & e-voucher',
    icon: Ticket,
    color: 'bg-orange-500',
    type: 'prepaid',
    customerLabel: 'Nomor HP / ID',
    customerPlaceholder: 'Nomor tujuan voucher',
    minLength: 5,
  },
  {
    id: 'game',
    label: 'Game Online',
    description: 'Top up game favorit Anda',
    icon: Gamepad2,
    color: 'bg-pink-500',
    type: 'prepaid',
    customerLabel: 'User ID / Nomor HP',
    customerPlaceholder: 'ID game atau nomor HP',
    minLength: 3,
  },
  {
    id: 'pln',
    label: 'Token PLN',
    description: 'Token listrik prabayar',
    icon: Zap,
    color: 'bg-yellow-500',
    type: 'prepaid',
    customerLabel: 'ID Pelanggan / No. Meter',
    customerPlaceholder: 'ID pelanggan PLN',
    minLength: 5,
  },
  {
    id: 'pln-pasca',
    label: 'PLN Pascabayar',
    description: 'Bayar tagihan listrik bulanan',
    icon: Receipt,
    color: 'bg-amber-500',
    type: 'pasca',
    customerLabel: 'ID Pelanggan PLN',
    customerPlaceholder: 'ID pelanggan / no. meter',
    minLength: 5,
  },
  {
    id: 'pdam-pasca',
    label: 'PDAM',
    description: 'Bayar tagihan air PDAM',
    icon: Droplets,
    color: 'bg-cyan-500',
    type: 'pasca',
    customerLabel: 'No. Pelanggan PDAM',
    customerPlaceholder: 'Nomor pelanggan / ID PDAM',
    minLength: 5,
  },
  {
    id: 'bpjs-pasca',
    label: 'BPJS',
    description: 'Bayar iuran BPJS Kesehatan',
    icon: HeartPulse,
    color: 'bg-rose-500',
    type: 'pasca',
    customerLabel: 'No. VA / Kartu BPJS',
    customerPlaceholder: 'Nomor VA atau kartu BPJS',
    minLength: 8,
  },
];

export const getServiceById = (id) => SERVICES.find((s) => s.id === id) || SERVICES[0];
